apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: dGVzdDEyMzQ=  # test1234
  mysql-username: c3ByaW5ndXNlcg==    # springuser
  mysql-password: VGhlUGFzc3dvcmQ=    # ThePassword
