name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Frontend
      run: |
        cd frontend
        chmod +x gradlew
        ./gradlew build

    - name: Build Backend
      run: |
        cd backend
        chmod +x gradlew
        ./gradlew build

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Frontend Docker image
      run: |
        cd frontend
        docker build -t rayanch1/numbers-frontend:latest .
        docker push rayanch1/numbers-frontend:latest

    - name: Build and Push Backend Docker image
      run: |
        cd backend
        docker build -t rayanch1/numbers-backend:latest .
        docker push rayanch1/numbers-backend:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl rollout restart deployment/frontend-deployment
        kubectl rollout restart deployment/backend-deployment
        kubectl rollout status deployment/frontend-deployment
        kubectl rollout status deployment/backend-deployment
